prefix rdfs:           <http://www.w3.org/2000/01/rdf-schema#>
prefix owl:            <http://www.w3.org/2002/07/owl#>
prefix dwc:            <http://rs.tdwg.org/dwc/terms/>
prefix taxref:         <http://taxref.mnhn.fr/lod/>
prefix taxrefprop:     <http://taxref.mnhn.fr/lod/property/>
prefix taxrefrk:       <http://taxref.mnhn.fr/lod/taxrank/>

# Add dwc:subgenus
construct { ?s dwc:subgenus ?tLabel. }
where {
    graph <http://taxref.mnhn.fr/lod/graph/classes/15.0> {
        ?t  a owl:Class;
            taxrefprop:hasRank taxrefrk:SubGenus;
            rdfs:label ?tLabel.
        ?s rdfs:subClassOf+ ?t.
    }
}

# Add dwc:genus
construct { ?s dwc:genus ?tLabel. } 
where {
    graph <http://taxref.mnhn.fr/lod/graph/classes/15.0> {
        ?t  a owl:Class;
            taxrefprop:hasRank taxrefrk:Genus;
            rdfs:label ?tLabel.
        ?s rdfs:subClassOf+ ?t.
    }
}

# Add dwc:subfamily
construct { ?s dwc:subfamily ?tLabel. }
where {
    graph <http://taxref.mnhn.fr/lod/graph/classes/15.0> {
        ?t  a owl:Class;
            taxrefprop:hasRank taxrefrk:SubFamily;
            rdfs:label ?tLabel.
        ?s rdfs:subClassOf+ ?t.
    }
}

# Add dwc:family
construct { ?s dwc:family ?tLabel. }
where {
    graph <http://taxref.mnhn.fr/lod/graph/classes/15.0> {
        ?t  a owl:Class;
            taxrefprop:hasRank taxrefrk:Family;
            rdfs:label ?tLabel.
        ?s rdfs:subClassOf+ ?t.
    }
}

# Add dwc:order
construct { ?s dwc:order ?tLabel. }
where {
    graph <http://taxref.mnhn.fr/lod/graph/classes/15.0> {
        ?t  a owl:Class;
            taxrefprop:hasRank taxrefrk:Order;
            rdfs:label ?tLabel.
        ?s rdfs:subClassOf+ ?t.
    }
}

# Add dwc:phylum
construct { ?s dwc:phylum ?tLabel. }
where {
    graph <http://taxref.mnhn.fr/lod/graph/classes/15.0> {
        ?t  a owl:Class;
            taxrefprop:hasRank taxrefrk:Phylum;
            rdfs:label ?tLabel.
        ?s rdfs:subClassOf+ ?t.
    }
}


# Add dwc:kingdom
construct { ?s dwc:kingdom ?tLabel. }
where {
    graph <http://taxref.mnhn.fr/lod/graph/classes/15.0> {
        ?t  a owl:Class;
            taxrefprop:hasRank taxrefrk:Kingdom;
            rdfs:label ?tLabel.
        ?s rdfs:subClassOf+ ?t.
    }
}
